"""create service_groups table

Revision ID: 5cd50497f4ff
Revises: ba3d8fe753a3
Create Date: 2025-08-18 17:28:50.534125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5cd50497f4ff'
down_revision: Union[str, None] = 'ba3d8fe753a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_groups',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_groups_id'), 'service_groups', ['id'], unique=False)
    op.create_index(op.f('ix_service_groups_slug'), 'service_groups', ['slug'], unique=True)
    op.alter_column('member_bank_accounts', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_member_bank_accounts_id'), 'member_bank_accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_bank_accounts_id'), table_name='member_bank_accounts')
    op.alter_column('member_bank_accounts', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_service_groups_slug'), table_name='service_groups')
    op.drop_index(op.f('ix_service_groups_id'), table_name='service_groups')
    op.drop_table('service_groups')
    # ### end Alembic commands ###
