"""create services table

Revision ID: b22b535ee07e
Revises: 8804c0f6a337
Create Date: 2025-08-21 19:42:01.905262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b22b535ee07e'
down_revision: Union[str, None] = '8804c0f6a337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('service_group_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('service_category_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('specifications', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_category_id'], ['service_categories.id'], ),
    sa.ForeignKeyConstraint(['service_group_id'], ['service_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
