"""create subscription table

Revision ID: 4fa526d91483
Revises: 6b4e16c92737
Create Date: 2025-09-02 12:39:03.543817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4fa526d91483'
down_revision: Union[str, None] = '6b4e16c92737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('plan_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('payment_mode_id', mysql.TINYINT(unsigned=True), nullable=False, comment='1 = Online, 2 = Offline'),
    sa.Column('member_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('locking_period', sa.String(length=255), nullable=False),
    sa.Column('bill_due_date', sa.Date(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', mysql.TINYINT(unsigned=True), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_member_id'), 'subscriptions', ['member_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_payment_mode_id'), 'subscriptions', ['payment_mode_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_payment_mode_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_member_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
