"""create plan_pricing table

Revision ID: 6b4e16c92737
Revises: a36e6520abf5
Create Date: 2025-08-25 16:09:31.778465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6b4e16c92737'
down_revision: Union[str, None] = 'a36e6520abf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_pricing',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('plan_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('currency_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_pricing_id'), 'plan_pricing', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_pricing_id'), table_name='plan_pricing')
    op.drop_table('plan_pricing')
    # ### end Alembic commands ###
