"""create tables

Revision ID: bafba711e7d1
Revises: 3c3cdcb36d2f
Create Date: 2025-08-20 16:32:49.076497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bafba711e7d1'
down_revision: Union[str, None] = '3c3cdcb36d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_categories_id'), 'service_categories', ['id'], unique=False)
    op.create_index(op.f('ix_service_categories_slug'), 'service_categories', ['slug'], unique=True)
    op.create_table('service_groups',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_groups_id'), 'service_groups', ['id'], unique=False)
    op.create_index(op.f('ix_service_groups_slug'), 'service_groups', ['slug'], unique=True)
    op.create_table('members',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('member_type_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_type_id'], ['member_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_table('member_addresses',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('member_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('country_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_bank_accounts',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('member_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('bank_holder_name', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('ifsc_code', sa.String(length=50), nullable=True),
    sa.Column('swift_code', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_bank_accounts_id'), 'member_bank_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_member_bank_accounts_member_id'), 'member_bank_accounts', ['member_id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               type_=mysql.INTEGER(unsigned=True),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               type_=mysql.BIGINT(display_width=20, unsigned=True),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_member_bank_accounts_member_id'), table_name='member_bank_accounts')
    op.drop_index(op.f('ix_member_bank_accounts_id'), table_name='member_bank_accounts')
    op.drop_table('member_bank_accounts')
    op.drop_table('member_addresses')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_service_groups_slug'), table_name='service_groups')
    op.drop_index(op.f('ix_service_groups_id'), table_name='service_groups')
    op.drop_table('service_groups')
    op.drop_index(op.f('ix_service_categories_slug'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_id'), table_name='service_categories')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
