"""init schema

Revision ID: c43046f42f80
Revises: 
Create Date: 2025-08-28 15:54:17.087539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c43046f42f80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_accounts',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_accounts_id'), 'business_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_business_accounts_slug'), 'business_accounts', ['slug'], unique=False)
    op.create_table('countries',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_table('currencies',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('slug', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_table('member_roles',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_member_roles_id'), 'member_roles', ['id'], unique=False)
    op.create_table('member_types',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_member_types_id'), 'member_types', ['id'], unique=False)
    op.create_table('project_statuses',
    sa.Column('id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_statuses_slug'), 'project_statuses', ['slug'], unique=True)
    op.create_table('service_categories',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_categories_id'), 'service_categories', ['id'], unique=False)
    op.create_index(op.f('ix_service_categories_slug'), 'service_categories', ['slug'], unique=True)
    op.create_table('service_groups',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_groups_id'), 'service_groups', ['id'], unique=False)
    op.create_index(op.f('ix_service_groups_slug'), 'service_groups', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('remember_token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('members',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('member_type_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_type_id'], ['member_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('business_account_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('project_status_id', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_account_id'], ['business_accounts.id'], ),
    sa.ForeignKeyConstraint(['project_status_id'], ['project_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_business_account_id'), 'projects', ['business_account_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_project_status_id'), 'projects', ['project_status_id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.create_table('user_email_verifications',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email_verifications_user_id'), 'user_email_verifications', ['user_id'], unique=False)
    op.create_table('member_addresses',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('member_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('country_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_bank_accounts',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('member_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('bank_holder_name', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('ifsc_code', sa.String(length=50), nullable=True),
    sa.Column('swift_code', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_bank_accounts_id'), 'member_bank_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_member_bank_accounts_member_id'), 'member_bank_accounts', ['member_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('member_role_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('member_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['member_role_id'], ['member_roles.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_members_member_id'), 'project_members', ['member_id'], unique=False)
    op.create_index(op.f('ix_project_members_member_role_id'), 'project_members', ['member_role_id'], unique=False)
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_member_role_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_member_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_member_bank_accounts_member_id'), table_name='member_bank_accounts')
    op.drop_index(op.f('ix_member_bank_accounts_id'), table_name='member_bank_accounts')
    op.drop_table('member_bank_accounts')
    op.drop_table('member_addresses')
    op.drop_index(op.f('ix_user_email_verifications_user_id'), table_name='user_email_verifications')
    op.drop_table('user_email_verifications')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_status_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_business_account_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_groups_slug'), table_name='service_groups')
    op.drop_index(op.f('ix_service_groups_id'), table_name='service_groups')
    op.drop_table('service_groups')
    op.drop_index(op.f('ix_service_categories_slug'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_id'), table_name='service_categories')
    op.drop_table('service_categories')
    op.drop_index(op.f('ix_project_statuses_slug'), table_name='project_statuses')
    op.drop_table('project_statuses')
    op.drop_index(op.f('ix_member_types_id'), table_name='member_types')
    op.drop_table('member_types')
    op.drop_index(op.f('ix_member_roles_id'), table_name='member_roles')
    op.drop_table('member_roles')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_business_accounts_slug'), table_name='business_accounts')
    op.drop_index(op.f('ix_business_accounts_id'), table_name='business_accounts')
    op.drop_table('business_accounts')
    # ### end Alembic commands ###
